### ISSUE TITLE
Waits in execution 

### ISSUE THREAD

**Issue by muzamilabbasi** [sakshisingla/Protractor-Non-Angular-Tests#3]
browser.driver.wait(function() {
     return browser.driver.findElement(by.id('id'))
              .then(function(elem) {
                elem.click();
                return true;
              });
  }, timeout_interval);

A little confused why do you have return true, after elem.click();

reference: https://github.com/sakshisingla/Protractor-Non-Angular-Tests/wiki/Creating-test-scripts-using-Protractor-for-non-angular-application

**Comment by bmrobin** [comment]
@muzamilabbasi you need the `return true;` because of the nested wrapper functions. without it, the inner function doesn't "complete" and the outer parent function will throw an error after `timeout_interval` has elapsed due to the function issued to `browser.driver.wait` not completing.

i know it looks like sequentially the code inside the function will have completed, but you have to return _something_ or the wait function will fail.
